= Какой должен быть первый шаг, когда вы хотите реализовать идею гениального стартапа

:source-highlighter: prettify
:icons: font
:toc: left
:experimental:
:numbered:
:homepage: http://antkorwin.com
Korovin Anatoliy <antkorwin@gmail.com>;  Home <http://antkorwin.com>


== Если вам близка одна из ситуаций ниже, то вам точно стоит дочитать до конца

- у вас есть идея?
- вы готовы начать работу над этим?
- может быть вы даже готовы вложить в это деньги, либо знаете кого-то кто верит в вас и готов так рискнуть
- вы считаете что нащупали идеальную нишу
- вы загорелись идеей реализовать что-то и думаете что разбогатеете
- вы думаете что будете первым, потому что еще никто не догадался так сделать




== PS

Этой статьей я не ставил себе задачу - отговорить вас от старта нового бизнеса, напротив, надеюсь что смог сэкономить вам время и деньги, для того чтобы стартовать более продуктивно. Айти-отрасль слишком переоценена, сейчас на рынке слишком много компаний "пустышек", они прожигают деньги инвесторов и никогда не принисут прибыли, потому что не решают никакой реальной задачи. Они не несут ценности киентам, потому что стали делать свои продукты в отрыве от запроса реального рынка и не проверив гипотезу.

Если этот материал был вам полезен, то подписаться на обновления можно в моем телеграм канале https://t.me/antkorwin_blog[t.me/antkorwin_blog] Возможно у вас были похожие ситуации, не стесняйтес написать в комментариях об этом.


include::../metrica.adoc[]