= Какой должен быть первый шаг, когда вы хотите реализовать идею гениального стартапа

:source-highlighter: prettify
:icons: font
:toc: left
:experimental:
:numbered:
:homepage: http://antkorwin.com
Korovin Anatoliy <antkorwin@gmail.com>;  Home <http://antkorwin.com>


== Придумал идею стартапа?

- готовы все бросить и начать работать над этим?
- готовы вложить в это деньги?
- считаете что нащупали идеальную нишу?
- загорелись идеей реализовать что-то и думаете что разбогатеете?
- вы думаете что будете первым, потому что еще никто не догадался так сделать?

== Не спеши нанимать программистов если

- не проверил гипотезу
- не получил свой первый доллар на этой идее, без привлечения программистов
- не знаешь пять-десять человек, которым продашь проект, как только он будет готов
(в идеале если они оплатят "предзаказ")
- не общался с ними о том нужен ли им этот продукт (custdev)

== Почему?

- делая продукт нужно очень хорошо понимать ЦА
- если вы сами не ЦА, то есть огромные шансы что продукт - не будет нужен ЦА
- если людям нарвится идея это не значит что они за нее будут платить
- лучше узнать есть ли рынок для продукта раньше, чем потратите на разработку кучу денег
- сэкономите деньги, которые можно потратить на реальный бизнес, а не на галлюцинации о том что вы придумали идею века 



== Ну и так чтобы максимально наглядно:

цена разработки портала: 3   - 30  миллионов руб
срок 					 2   - 12  мес

цена проверки гипотезы:  100 - 500 тыс       руб
срок 					 1   - 4   недели

== Выводы очень простые 

- нужно искать хаки, как дешево и быстро проверять гипотезы
- вкладываться только в то что подтвердилось

PS
иногда очень сложно, даже самому следовать этим правилам. 
Не один раз наступал на эти грабли, пишите в комментариях, если интересно узнать про такие истории.





== Если вам близка одна из ситуаций ниже, то вам точно стоит дочитать до конца

- у вас есть идея?
- вы готовы начать работу над этим?
- может быть вы даже готовы вложить в это деньги, либо знаете кого-то кто верит в вас и готов так рискнуть
- вы считаете что нащупали идеальную нишу
- вы загорелись идеей реализовать что-то и думаете что разбогатеете
- вы думаете что будете первым, потому что еще никто не догадался так сделать




== PS

Этой статьей я не ставил себе задачу - отговорить вас от старта нового бизнеса, напротив, надеюсь что смог сэкономить вам время и деньги, для того чтобы стартовать более продуктивно. Айти-отрасль слишком переоценена, сейчас на рынке слишком много компаний "пустышек", они прожигают деньги инвесторов и никогда не принисут прибыли, потому что не решают никакой реальной задачи. Они не несут ценности киентам, потому что стали делать свои продукты в отрыве от запроса реального рынка и не проверив гипотезу.

Если этот материал был вам полезен, то подписаться на обновления можно в моем телеграм канале https://t.me/antkorwin_blog[t.me/antkorwin_blog] Возможно у вас были похожие ситуации, не стесняйтес написать в комментариях об этом.


include::../metrica.adoc[]