= На какие грабли мы наступили, перед тем как систематизировали работу со сметами (топ 3 проблем в оценке трудозатрат на айти проект)

:source-highlighter: prettify
:icons: font
:toc: left
:experimental:
:numbered:
:homepage: http://antkorwin.com
Korovin Anatoliy <antkorwin@gmail.com>;  Home <http://antkorwin.com>



== Чем отличается хорошая смета от плохой и зачем тратить время на  сметы

Если вы руководитель компании, которая занимается проектной работой, то оценка стоимости проекта для заказчика - это неотъемлимая часть вашей работы. Этот процесс может быть системным или нет. Расскажу на своем опыте, еще не так давно, я не придавал этому большого значения. Когда мне нужно было оценить разработку проекта, я либо самостоятельно пробегался по ТЗ и выдавал оценку, опираясь на свой опыт, либо делегировал эту задачу кому-то из сотрудников. Без построения системного подхода к сметам, очень велик соблазн обсуждать оценку проекта в чате или почте. Часто бывает так, что поняв бюджет заказчик идет согласовывать закупку, в больших компаниях это может занять больше года. Так вот, когда через год к нам возвращался тот же самый клиент, очень сложно было восстановить все детали оценки проекта из сотен чатов и переписки в почте.

Какие проблемы это сулит:

- если у вас нет детализации расчетов, то вы не можете объективно скорректировать финальный результат. Вы сами не понимаете логику того, кто оценивал работы. Представим ситуацию, нужно написать импортозамещенный аналог skype, технический специалист скинул вам оценку #100 миллионов рублей, 12 мес#. Все что можно сделать с этой оценкой - это бездумно умножить ее на 2 или на 3, я знаю одного руководителя который любит умножать на Pi такие вещи. А что если заказчик скажет что у них есть только 90 миллионов? у вас нет никакого маневра на этот случай, вы не можете сходу предложить что-то выкинуть потому что нет детализации и нормальной сметы.

- следующая проблема - это необходимость пересчитать плюс-минус тоже самое, спустя пару месяцев. Вполне реальный кейс: ваш заказчик ушел согласовывать бюджет на полгода, а когда ему одобрили закупку у вас произошли изменения в команде, кто-то вырос по карьерной лестнице и теперь его участие в проекте стоит для вас дороже, а кто-то недай бог уволился, еще хужее может быть только если ушел тот самый человек, который считал смету, с таким я тоже пару раз сталкивался, если все что он оставил после себя было число - 100 миллионов, то вам придется заново разбирать ТЗ, тратить уйму времении на это, и скорее всего ваша оценка не совпадет с предыдущеей. В итоге клиент - не доволен, потому что ему опять деньги согласовывать на закупку, задачу свою он не решил. Вы не доввольны - потому что не заработали, а времени потратили х2 или даже х3 от того что можно было. Будь у вас на руках детальная смета проекта, вы бы понимали логику рассчета и могли ее легко скорректировать, ниже мы рассмотрим как сделать такую смету.

- еще оддна проблема в несистемном подходе к этому вопросу - это процесс поиска в чатах и переписке нюансов этого проекта и списка рисков. Возможно скидывая цену #100 миллионов# вам написали еще и пару комментариев что-то типа: #если им нужно поддержку iOS то есть вероятность не успеть в сроок# Или что-то такое #если мы отвечаем за публикацию приложения в сторе, то нам нужна enterprise учетка apple#. Проблема в том что спустя 2,3,4 месяца после оценки очень сложно искать такие сообщения в чате.




== Ending


Как обычно, шаблон для первого шага подготовки маркетинговых материалов и формирования УТП вы можете найти в моем телеграм канале: https://t.me/antkorwin_blog[t.me/antkorwin_blog]


include::../metrica.adoc[]