= УТП на примерах
:source-highlighter: prettify
:icons: font
:toc: left
:experimental:
:numbered:
:homepage: http://antkorwin.com
Korovin Anatoliy <antkorwin@gmail.com>;  Home <http://antkorwin.com>



== Пример истории

Давайте представим ситуацию, что компания “ромашка” разрабатывает CRM для автосервисов. Таких продуктов на рынке очень много. Как мы можем помочь Ивану сформировать маркетинговую компанию для их продукта?

первый шаг: изучить продукт 
какие характеристики у CRM, какие есть уникальные фичи с точки зрения фаундера, product-менеджера, отдела маркетинга и может даже разработчиков. Не принимать за догму все что услышите. 
второй шаг: изучить тех кто уже покупает наши услуги
зачем купили, какая была задача, чем пользуются, какие впечатления, кто принимал решение о покупке
третий шаг: найти и изучить (seek and destroy) конкурентов. Вот тут может случиться интересное, возможно рассказы фаундера и ваших сотрудников не будут совпадать с рынком, вполне вероятно что есть аналогичные решения, и ваши фичи не уникальны, либо маркетинг конкурентов работает лучше. У вас могут появиться правильные вопросы чтобы вернуться с ними к вашей команде и обсудить результаты вашего исследования.

Вернемся к нашей задаче, как позиционировать CRM для автосервисов. Вот несколько вариантов:

Drive-CRM увеличивает возврат клиентов на 15%, при помощи AI, который советует клиентам помыть авто в самое удобное время и предсказывает когда нужно будет заехать на мойку в следующий раз.
Drive CRM на вашу мойку будут возвращаться чаще!
