= Как писать тесты
:source-highlighter: prettify
:icons: font
:toc:
:experimental:
:numbered:
:homepage: http://antkorwin.com
Korovin Anatoliy <antkorwin@gmail.com>;  Home <http://antkorwin.com>
// START OF CONTENT

## Тестирование специфичных для БД кейсов
### тестируем хранимые процедуры
### custom query
### подготовка и проверка тестовых данных в БД
### тестовый контекст в спринге DataJpa
### mongodb + testcontainers

## Cache
### пример как тестировать работу кэша в спринге

## Cloud и микросервисы
### пример тестирования клиента для rest сервиса на restTemplate
### пример тестирования для feign client


## Concurrency
пример тестирования АПИ, которое должно работать под конкурентными запросами

[source, java]
----
 @Test
 public void testParallelCreatedSubTasks() throws Exception {

     Set<Integer> actualResult =
                     IntStream.range(0, 1000)
                              .boxed()
                              .parallel()
                              .map(index -> {
                                  try {
                                      // Act
                                      MvcRequester.on(mockMvc)
                                                  .to(CREATE_SUBTASK_URL, TASK_ID)
                                                  .post()
                                                  .doExpect(status().isOk());
                                      return 200;
                                  } catch (Exception e) {
                                      System.out.println(e);
                                      return 500;
                                  }
                              }).collect(Collectors.toSet());

     // Assert
     Assertions.assertThat(actualResult).containsOnly(200);
 }
----


## Async

### wrong way (stop using Thread.sleep(1000))

[source, java]
----
@Test
void testCreateTaskAndSendEvent() {
    // Act
    taskService.create(TASK_TITILE, TASK_ESTIMATE);

    await().atMost(10, TimeUnit.SECONDS)
           .untilAsserted(() -> verify(reportService).createTask(captor.capture()));

    // Arrange
    assertThat(captor.getValue())
            .extracting(Task::getTitle, Task::getEstimate)
            .contains(TASK_TITILE, TASK_ESTIMATE);
}
----

- как написать ожидание создания записи в БД

- как ждать на verify блоке теста

- ожидание пока assert не станет true

- деадлоки и таймауты

### JMS / AMQP

- пример тестирования RabbitMq в докере(testcontainers)
+ ожидание обработки ивента

### Spring Events

- как написать тест ожидающий поступления ивента

### Scheduler

- как тестировать паланировщики

- стоит менять настройки таймаутов для тестов

## Performance
### JMH
- пример теста перформанса ConcurrentHashMap
- какая задача тестов перформанса
- нужно знать тестовое окружение


## Report systems

- пример тестирования отчета построенного в JasperReports
- что даст юнит тест, а что интеграционный? и нужны ли и те и другие
- подход 1: делаем экстракт данных и сравниваем их с ожидаемыми
- подход 2: сравниваем файлы с эталоном
- плюсы / минусы



## E2E
- Тестирование в продакшене
- задания и отчеты при неудачах


## Junit5

### избавляемся от иерархии (заворачиваем extendswith в метаанотации)

### тестовые интерфейсы (BaseCrud)

### группировка методов


// END OF CONTENT
include::../metrica.adoc[]

++++
<div id="disqus_thread"></div>
<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = 'antkorwin.com';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = 'TITLE'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://antkorwin.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
++++
