= Synchronized by multiple keys
:source-highlighter: prettify
:icons: font
:toc:
:experimental:
:numbered:
:homepage: http://antkorwin.com
Korovin Anatoliy <antkorwin@gmail.com>;  Home <http://antkorwin.com>
// START OF CONTENT

## Intro to the problem

Here you can see the wrong sequence:
[plantuml]
....
actor Bob
control AutoPayment
Bob -> Thread_1 : get 100$
activate Thread_1 #orange
Thread_1 -> Account_Bob : get balance
Account_Bob --> Thread_1 : balance = 1000$
AutoPayment -> Thread_2 : move from Bob to Alice 100$, every month
activate Thread_2 #DarkKhaki
Thread_2 -> Account_Bob : get balance
Account_Bob --> Thread_2 : balance = 1000$
Thread_1 -> Account_Bob : withdraw 100$
activate Account_Bob #red
Account_Bob --> Thread_1 : balance = 900$
Thread_1 --> Bob : give out 100$
deactivate Account_Bob
deactivate Thread_1
Thread_2 -> Account_Alice : get balance
Account_Alice --> Thread_2 : balance = 200$
Thread_2 -> Account_Bob : move 100$ to Alice
activate Account_Bob #red
Account_Bob --> Thread_2 :  balance = 900$
deactivate Account_Bob
Thread_2 -> Account_Alice : got 100$ from Bob
activate Account_Alice #red
Account_Alice --> Thread_2 : balance = 300$
deactivate Account_Alice
Thread_2 --> AutoPayment :'   successful
deactivate Account_Alice
deactivate Thread_2
control AutoPayment
....
