= How to use a curle
:source-highlighter: prettify
:icons: font
:toc: left
:experimental:
:numbered:
:homepage: http://antkorwin.com
Korovin Anatoliy <antkorwin@gmail.com>;  Home <http://antkorwin.com>
// START OF CONTENT


## Obtain a new token from the OAuth service:

[source, sh]
----
curl 'http://AUTH_SERVICE/oauth/token' \
-H "Authorization: Basic $(echo -n 'client_id:secret_id'| base64)" \
--data 'grant_type=password&username=test%40test.com&password=q1w2e3r4'
----


`AUTH_SERVICE`  - ip and port of your auth-service application

`client_id` & `secret_id` - the oauth scope settings

`grant_type` - the grant type of oauth scope


And we got the next result:

[source, json]
----
{
  "access_token":"b676836e-2cad-48c6-8ac9-cfa825768438",
  "token_type":"bearer",
  "refresh_token":"c167a434-6310-47a5-bec3-068f94856b97",
  "expires_in":79834,
  "scope":"default"
}
----


## How to a new token and use it

[source, sh]
----
$ curl -v 'http://SOME_SERVICE/secured-api' \
-H 'Accept: application/json, text/plain, */*'  \
-H "Authorization: Bearer $(curl 'http:/AUTH_SERVICE/oauth/token' \
-H 'Accept: application/json, text/plain, */*'  \
-H "Authorization: Basic $(echo -n 'client_id:secret_id'| base64)" \
-H 'Content -Type: application/x-www-form-urlencoded' \
--data 'grant_type=password&username=test%40test.com&password=q1w2e3r4' \
| awk -F':' '{print $2}' | awk -F, '{print $1}' | sed -e 's/"//g' )"
----


// END OF CONTENT
include::../metrica.adoc[]

++++
<div id="disqus_thread"></div>
<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = 'antkorwin.com';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = 'curl'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://antkorwin.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
++++
